<?php

namespace Database\Seeders;

use App\Models\Dish;
use App\Models\DishCategory;
use Illuminate\Database\Seeder;

class DishSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $mainDishesCategory = DishCategory::where('slug', 'osnovnye-blyuda')->first();
        $saladsCategory = DishCategory::where('slug', 'salaty')->first();
        $appetizersCategory = DishCategory::where('slug', 'zakuski')->first();
        $soupsCategory = DishCategory::where('slug', 'supy')->first();
        $dessertsCategory = DishCategory::where('slug', 'deserty')->first();

        $dishes = [
            // Основные блюда
            [
                'name_ru' => 'Боул с курицей, овощами и арахисовым соусом',
                'name_ka' => 'ბოული ქათმით, ბოსტნეულით და არაქისის სოუსით',
                'description_ru' => 'Куриное филе запечённое, гречка, перец болгарский запечённый, картофель запечённый, брокколи + арахисовый соус',
                'description_ka' => 'შემწვარი ქათმის ფილე, ქერი, შემწვარი ბულგარული წიწაკა, შემწვარი კარტოფილი, ბროკოლი + არაქისის სოუსი',
                'price' => 26.00,
                'discount_price' => null,
                'dish_category_id' => $mainDishesCategory->id,
                'weight_volume' => '325 г',
                'calories' => 315,
                'proteins' => 31.00,
                'fats' => 4.00,
                'carbohydrates' => 34.00,
                'fiber' => 8.00,
                'sauce_name_ru' => 'Арахисовый соус',
                'sauce_name_ka' => 'არაქისის სოუსი',
                'sauce_weight_volume' => '40 г',
                'sauce_calories' => 85,
                'sauce_proteins' => 4.10,
                'sauce_fats' => 7.60,
                'sauce_carbohydrates' => 2.70,
                'sauce_fiber' => 0.50,
                'sort_order' => 1,
            ],
            [
                'name_ru' => 'Боул из норвежского лосося, диким и цельнозерновым рисом',
                'name_ka' => 'ბოული ნორვეგიული ორაგულით, ველური და მთელმარცვლიანი ბრინჯით',
                'description_ru' => 'Норвежский лосось, смесь дикого и цельнозернового риса, эдамаме, авокадо, огурец, петрушка + медово-цитрусовый соус',
                'description_ka' => 'ნორვეგიული ორაგული, ველური და მთელმარცვლიანი ბრინჯის ნარევი, ედამამე, ავოკადო, კიტრი, ოხრახუში + თაფლიანი-ციტრუსოვანი სოუსი',
                'price' => 38.00,
                'discount_price' => null,
                'dish_category_id' => $mainDishesCategory->id,
                'weight_volume' => '342 г',
                'calories' => 440,
                'proteins' => 32.00,
                'fats' => 20.00,
                'carbohydrates' => 38.00,
                'fiber' => 7.00,
                'sauce_name_ru' => 'Медово-цитрусовый соус',
                'sauce_name_ka' => 'თაფლიანი-ციტრუსოვანი სოუსი',
                'sauce_weight_volume' => '40 г',
                'sauce_calories' => 22,
                'sauce_proteins' => 0.37,
                'sauce_fats' => 0.09,
                'sauce_carbohydrates' => 5.00,
                'sauce_fiber' => 0.10,
                'sort_order' => 2,
            ],
            [
                'name_ru' => 'Боул с говядиной Tenderloin, бататом и красной чечевицей',
                'name_ka' => 'ბოული საქონლის ხორცით Tenderloin, ბატატით და წითელი ოსპით',
                'description_ru' => 'Говядина Tenderloin, батат, чечевица, помидоры черри, стручковая фасоль, авокадо + Hot honey sauce',
                'description_ka' => 'საქონლის ხორცი Tenderloin, ბატატი, ოსპი, პომიდორი ჩერი, სტრიქონის ლობიო, ავოკადო + ცხარე თაფლიანი სოუსი',
                'price' => 39.00,
                'discount_price' => null,
                'dish_category_id' => $mainDishesCategory->id,
                'weight_volume' => '339 г',
                'calories' => 400,
                'proteins' => 25.00,
                'fats' => 17.00,
                'carbohydrates' => 37.00,
                'fiber' => 10.00,
                'sauce_name_ru' => 'Hot honey sauce',
                'sauce_name_ka' => 'ცხარე თაფლიანი სოუსი',
                'sauce_weight_volume' => '40 г',
                'sauce_calories' => 86,
                'sauce_proteins' => 0.08,
                'sauce_fats' => 0.04,
                'sauce_carbohydrates' => 21.70,
                'sauce_fiber' => 0.10,
                'sort_order' => 3,
            ],
            [
                'name_ru' => 'Боул с королевской креветкой, мозаикой из тофу и огурца',
                'name_ka' => 'ბოული სამეფო კრევეტით, ტოფუსა და კიტრის მოზაიკით',
                'description_ru' => 'Королевские креветки, мозаика из тофу и огурца, рис цельнозерновой, авокадо, томаты черри, стручковая фасоль, петрушка',
                'description_ka' => 'სამეფო კრევეტები, ტოფუსა და კიტრის მოზაიკა, მთელმარცვლიანი ბრინჯი, ავოკადო, პომიდორი ჩერი, სტრიქონის ლობიო, ოხრახუში',
                'price' => 39.00,
                'discount_price' => null,
                'dish_category_id' => $mainDishesCategory->id,
                'weight_volume' => '377 г',
                'calories' => 340,
                'proteins' => 32.00,
                'fats' => 8.00,
                'carbohydrates' => 33.00,
                'fiber' => 7.00,
                'sauce_name_ru' => 'Соус',
                'sauce_name_ka' => 'სოუსი',
                'sauce_weight_volume' => '40 г',
                'sauce_calories' => 20,
                'sauce_proteins' => 0.50,
                'sauce_fats' => 0.50,
                'sauce_carbohydrates' => 3.00,
                'sauce_fiber' => 0.10,
                'sort_order' => 4,
            ],
            [
                'name_ru' => 'Боул с куриным бедром Souvlaki и запеченным картофелем',
                'name_ka' => 'ბოული ქათმის ბარკლით Souvlaki და შემწვარი კარტოფილით',
                'description_ru' => 'Куриное бедро souvlaki, картофель запеченный, брокколи, цветная капуста, томаты черри, огурец, укроп + соус дзадзики',
                'description_ka' => 'ქათმის ბარკალი souvlaki, შემწვარი კარტოფილი, ბროკოლი, ყვავილოვანი კომბოსტო, პომიდორი ჩერი, კიტრი, კამა + სოუსი ძაძიკი',
                'price' => 25.00,
                'discount_price' => null,
                'dish_category_id' => $mainDishesCategory->id,
                'weight_volume' => '340 г',
                'calories' => 315,
                'proteins' => 27.00,
                'fats' => 13.00,
                'carbohydrates' => 23.00,
                'fiber' => 7.00,
                'sauce_name_ru' => 'Дзадзики',
                'sauce_name_ka' => 'ძაძიკი',
                'sauce_weight_volume' => '40 г',
                'sauce_calories' => 25,
                'sauce_proteins' => 3.40,
                'sauce_fats' => 1.10,
                'sauce_carbohydrates' => 1.30,
                'sauce_fiber' => 0.20,
                'sort_order' => 5,
            ],
            // Салаты
            [
                'name_ru' => 'Салат с курицей в лимонном соусе, мягким творогом и зеленью',
                'name_ka' => 'სალათი ქათმით ლიმონის სოუსში, რბილი ყველითა და მწვანილით',
                'description_ru' => 'Куриное филе, салат лола + айсберг, рукола, огурец, томаты черри, тыквенные семечки + творожный соус',
                'description_ka' => 'ქათმის ფილე, სალათი ლოლა + აისბერგი, რუკოლა, კიტრი, პომიდორი ჩერი, გოგრის თესლი + ყველის სოუსი',
                'price' => 23.00,
                'discount_price' => null,
                'dish_category_id' => $saladsCategory->id,
                'weight_volume' => '218 г',
                'calories' => 199,
                'proteins' => 28.00,
                'fats' => 6.00,
                'carbohydrates' => 7.00,
                'fiber' => 4.00,
                'sauce_name_ru' => 'Творожный соус',
                'sauce_name_ka' => 'ყველის სოუსი',
                'sauce_weight_volume' => '40 г',
                'sauce_calories' => 38,
                'sauce_proteins' => 3.40,
                'sauce_fats' => 2.00,
                'sauce_carbohydrates' => 1.40,
                'sauce_fiber' => 0.10,
                'sort_order' => 1,
            ],
            [
                'name_ru' => 'Салат с тунцом татаки, авокадо и манговым соусом',
                'name_ka' => 'სალათი ტუნით ტატაკი, ავოკადოთი და მანგოს სოუსით',
                'description_ru' => 'Тунец татаки, авокадо, салат лола + айсберг, стручковая фасоль, огурец, морковь + соус манго-мята',
                'description_ka' => 'ტუნა ტატაკი, ავოკადო, სალათი ლოლა + აისბერგი, სტრიქონის ლობიო, კიტრი, სტაფილო + მანგოს-პიტნის სოუსი',
                'price' => 38.00,
                'discount_price' => null,
                'dish_category_id' => $saladsCategory->id,
                'weight_volume' => '268 г',
                'calories' => 234,
                'proteins' => 29.00,
                'fats' => 7.00,
                'carbohydrates' => 6.00,
                'fiber' => 7.00,
                'sauce_name_ru' => 'Манго-мята',
                'sauce_name_ka' => 'მანგო-პიტნა',
                'sauce_weight_volume' => '40 г',
                'sauce_calories' => 24,
                'sauce_proteins' => 0.30,
                'sauce_fats' => 0.10,
                'sauce_carbohydrates' => 5.20,
                'sauce_fiber' => 0.20,
                'sort_order' => 2,
            ],
            [
                'name_ru' => 'Чука салат с арахисовым соусом',
                'name_ka' => 'ჩუკა სალათი არაქისის სოუსით',
                'description_ru' => 'Чука, лимон, кунжут + арахисовый соус',
                'description_ka' => 'ჩუკა, ლიმონი, სეზამი + არაქისის სოუსი',
                'price' => 19.00,
                'discount_price' => null,
                'dish_category_id' => $saladsCategory->id,
                'weight_volume' => '142 г',
                'calories' => 102,
                'proteins' => 1.30,
                'fats' => 2.20,
                'carbohydrates' => 19.00,
                'fiber' => 2.00,
                'sauce_name_ru' => 'Арахисовый соус',
                'sauce_name_ka' => 'არაქისის სოუსი',
                'sauce_weight_volume' => '40 г',
                'sauce_calories' => 85,
                'sauce_proteins' => 4.10,
                'sauce_fats' => 7.60,
                'sauce_carbohydrates' => 2.70,
                'sauce_fiber' => 0.50,
                'sort_order' => 3,
            ],
            // Закуски
            [
                'name_ru' => 'Хумус со свежими овощами',
                'name_ka' => 'ჰუმუსი ახალი ბოსტნეულით',
                'description_ru' => 'Хумус, огурец, перец болгарский, морковь, сельдерей',
                'description_ka' => 'ჰუმუსი, კიტრი, ბულგარული წიწაკა, სტაფილო, ნიახური',
                'price' => 17.00,
                'discount_price' => null,
                'dish_category_id' => $appetizersCategory->id,
                'weight_volume' => '222 г',
                'calories' => 159,
                'proteins' => 9.80,
                'fats' => 7.50,
                'carbohydrates' => 16.00,
                'fiber' => 5.00,
                'sort_order' => 1,
            ],
            // Супы
            [
                'name_ru' => 'Томатный крем суп с чечевичным хлебом',
                'name_ka' => 'ნაღების კრემ სუპი ოსპის პურით',
                'description_ru' => 'Томат, болгарский перец, йогурт, чечевичный хлеб',
                'description_ka' => 'პომიდორი, ბულგარული წიწაკა, იოგურტი, ოსპის პური',
                'price' => 16.00,
                'discount_price' => null,
                'dish_category_id' => $soupsCategory->id,
                'weight_volume' => '360 г',
                'calories' => 159,
                'proteins' => 9.80,
                'fats' => 7.50,
                'carbohydrates' => 16.00,
                'fiber' => 4.00,
                'sort_order' => 1,
            ],
            [
                'name_ru' => 'Мисо суп',
                'name_ka' => 'მისო სუპი',
                'description_ru' => 'Мисо паста, вакаме, тофу, рис',
                'description_ka' => 'მისო პასტა, ვაკამე, ტოფუ, ბრინჯი',
                'price' => 20.00,
                'discount_price' => null,
                'dish_category_id' => $soupsCategory->id,
                'weight_volume' => '393 г',
                'calories' => 166,
                'proteins' => 10.80,
                'fats' => 5.30,
                'carbohydrates' => 20.10,
                'fiber' => 2.00,
                'sort_order' => 2,
            ],
            [
                'name_ru' => 'Мисо суп с королевскими креветками',
                'name_ka' => 'მისო სუპი სამეფო კრევეტებით',
                'description_ru' => 'Мисо паста, королевские креветки, вакаме, тофу, рис',
                'description_ka' => 'მისო პასტა, სამეფო კრევეტები, ვაკამე, ტოფუ, ბრინჯი',
                'price' => 30.00,
                'discount_price' => null,
                'dish_category_id' => $soupsCategory->id,
                'weight_volume' => '443 г',
                'calories' => 215,
                'proteins' => 22.00,
                'fats' => 5.50,
                'carbohydrates' => 20.00,
                'fiber' => 2.00,
                'sort_order' => 3,
            ],
            [
                'name_ru' => 'Мисо суп с норвежским лососем',
                'name_ka' => 'მისო სუპი ნორვეგიული ორაგულით',
                'description_ru' => 'Мисо паста, норвежский лосось, вакаме, тофу, рис',
                'description_ka' => 'მისო პასტა, ნორვეგიული ორაგული, ვაკამე, ტოფუ, ბრინჯი',
                'price' => 32.00,
                'discount_price' => null,
                'dish_category_id' => $soupsCategory->id,
                'weight_volume' => '443 г',
                'calories' => 265,
                'proteins' => 20.50,
                'fats' => 12.00,
                'carbohydrates' => 19.00,
                'fiber' => 2.00,
                'sort_order' => 4,
            ],
            // Десерты
            [
                'name_ru' => 'Клубничный чиа пудинг с фисташкой и йогуртом',
                'name_ka' => 'მარწყვის ჩია პუდინგი ფისტიშკითა და იოგურტით',
                'description_ru' => 'Греческий йогурт, пюре из свежей клубники, клубника, фисташка, чиа',
                'description_ka' => 'ბერძნული იოგურტი, ახალი მარწყვის პიურე, მარწყვი, ფისტიშკა, ჩია',
                'price' => 14.00,
                'discount_price' => null,
                'dish_category_id' => $dessertsCategory->id,
                'weight_volume' => '285 г',
                'calories' => 252,
                'proteins' => 13.20,
                'fats' => 11.80,
                'carbohydrates' => 22.30,
                'fiber' => 5.00,
                'sort_order' => 1,
            ],
            [
                'name_ru' => 'Манго чиа пудинг с фисташкой и йогуртом',
                'name_ka' => 'მანგოს ჩია პუდინგი ფისტიშკითა და იოგურტით',
                'description_ru' => 'Греческий йогурт, пюре из свежего манго, манго, фисташка, чиа',
                'description_ka' => 'ბერძნული იოგურტი, ახალი მანგოს პიურე, მანგო, ფისტიშკა, ჩია',
                'price' => 17.00,
                'discount_price' => null,
                'dish_category_id' => $dessertsCategory->id,
                'weight_volume' => '285 г',
                'calories' => 272,
                'proteins' => 13.30,
                'fats' => 11.80,
                'carbohydrates' => 26.90,
                'fiber' => 5.00,
                'sort_order' => 2,
            ],
        ];

        foreach ($dishes as $dish) {
            Dish::firstOrCreate(
                [
                    'name_ru' => $dish['name_ru'],
                    'dish_category_id' => $dish['dish_category_id'],
                ],
                $dish
            );
        }
    }
}
